Спринт №22.
Myachkaa/PlaylistMaker pull request #15
Opened 2024-09-03 15:47 UTC by Myachkaa

Добавлена логика отображения и добавления плейлистов, добавления треков в плейлисты.

2024-09-05 14:20 UTC, DmitrijEgorow commented
- [ ] Неправильные отступы между плейлистами, слева-справа-снизу, заголовка от обложки
![Screenshot_20240905_210419](https://github.com/user-attachments/assets/064d72fa-e270-493a-8506-8b27433584c0)

2024-09-05 14:21 UTC, DmitrijEgorow commented
- [ ] 	Нужно добавить скругления углов обложки, но сохранить обрезку с соотношением сторон 1:1

![Screenshot_20240905_210531](https://github.com/user-attachments/assets/8842870e-4b6b-4018-9795-bf9482232345)

2024-09-05 14:21 UTC, DmitrijEgorow commented
- [ ] Поломалось воспроизведение после сворачивания приложения

https://github.com/user-attachments/assets/842c7c4a-6619-4b9d-a501-8824347c2a0d

2024-09-05 14:30 UTC, DmitrijEgorow requested changes

2024-09-05 14:30 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/ui/activity/CreatePlaylistFragment.kt
> +        toast.setGravity(Gravity.BOTTOM or Gravity.FILL_HORIZONTAL, 0, 100)
[no-op](https://developer.android.com/reference/android/widget/Toast#setGravity(int,%20int,%20int))

2024-09-05 14:30 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/ui/activity/CreatePlaylistFragment.kt
> +        toast.view = layout
Можно воспользоваться extension-функцией, например, `apply`

2024-09-05 14:30 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/ui/activity/PlaylistTrackViewHolder.kt
> +        if (trackQty % 100 in 5..20) return "$trackQty треков"
При таком подходе возникнут проблемы при локализации

2024-09-05 14:30 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/ui/activity/PlaylistViewHolder.kt
> +        if (trackQty % 10 == 1) return "$trackQty трек"
Зачем дублировать код?

2024-09-05 14:30 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/ui/view_model/CreatePlaylistViewModel.kt
> +            } catch (e: Exception) {
Можно ловить только специфичную имплементацию Exception?

2024-09-11 15:59 UTC, DmitrijEgorow commented
https://github.com/user-attachments/assets/30558c27-cb6b-46a5-8253-aaeec7d16b56

2024-09-11 16:11 UTC, Myachkaa commented
@DmitrijEgorow Привет! Исправила, кинула коммит

2024-09-12 10:00 UTC, merged